name = "Lírio Pop"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "Tema Hugo legível e divertido com as paletas Rosé Pine Dawn e Moon."
homepage = "https://monique.dev"
tags = ["blog", "colorful", "mobile-first", "darkmode", "a11y"]
features = ["responsive", "adaptive-color", "legible-type", "rss", "toc"]
min_version = "0.111.3"

[author]
  name = "Monique + ChatGPT"
  homepage = "https://monique.dev"

[params]
  colorScheme = "auto" # light | dark | auto
  showTOC = true
  showDates = true
  showEstimatedReadingTime = true
